name: Daily Preply Scraper
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          # Install chromium and chromium-driver packages
          sudo apt-get install -y chromium-browser chromium-chromedriver
      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium chromium-chromedriver

      - name: Run script
        env:
          PATH: /usr/bin:$PATH  # Ensure ChromeDriver can be found
        run: python preply_scraper.py
