name: Daily Preply Scraper

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests selenium
          # any other dependencies

      - name: Run script
        run: python preply_scraper.py
